#ifndef BOARD_CFG_H
#define BOARD_CFG_H

#define USART1_TX_PIN_PORT GPIO_A
#define USART1_TX_PIN_NUMBER 9

#define USART1_RX_PIN_PORT GPIO_A
#define USART1_RX_PIN_NUMBER 10

#define USART2_TX_PIN_PORT GPIO_A
#define USART2_TX_PIN_NUMBER 2

#define USART2_RX_PIN_PORT GPIO_A
#define USART2_RX_PIN_NUMBER 3

#define LED_GPIO_PORT GPIO_A
#define LED_GPIO_PIN 5

#define DHT_GPIO_PORT GPIO_C
#define DHT_GPIO_PIN  7

#define STDIO USART_2

#define DEFAULT_BAUD_RATE 115200

#endif
