#ifndef BOARD_CFG_H
#define BOARD_CFG_H

#define USART1_PORT GPIO_A
#define USART1_TX_PIN 9
#define USART1_RX_PIN 10

#define USART2_PORT GPIO_A
#define USART2_TX_PIN 2
#define USART2_RX_PIN 15

#define LED_GPIO_PORT GPIO_B
#define LED_GPIO_PIN 3

#define DHT_GPIO_PORT GPIO_A
#define DHT_GPIO_PIN  7

#define STDIO USART_2

#define DEFAULT_BAUD_RATE 38400

#endif
